function Language() {
    const LanguageList =
        ["简体中文",
        "翻譯中文",
        "English",
        "日本語"];
     
    const LanguageText = {
        0 : 
            ["语言",
            "简体中文",
            "初始化设置..",
            "模块加载错误",
            "未找到合适配置, 已加载默认配置!",
            "加载配置文件失败! 已自动加载默认配置!",
            "保存用户游戏配置成功",
            "错误",
            "没有找到MIDI设备, 点击确定重试, 点击取消退出",
            "选择MIDI设备",
            "打开设备失败",
            "等待设备连接…",
            "您取消了选择",
            "MIDI连接失败！",
            "MIDI连接成功！",
            "此MIDI设备没有可用的端口",
            "选择MIDI端口",
            "等待无障碍服务...",
            "请打开 ",
            " 的无障碍权限!",
            "无障碍权限已开启!",
            "无障碍服务已启动",
            "请打开 ",
            " 的悬浮窗权限!",
            "悬浮窗权限已开启",
            "请点击",
            "最左上角按键的中心",
            "最右下角按键的中心",
            "定位第",
            "行 第",
            "个按键",
            "当前坐标：",
            "，点击'确定'结束, 点击'取消'重新获取",
            "坐标不准? 手机上下翻转后再尝试",
            "或 手指直接点击按键位置 忽略十字线位置偏差",
            "点击调整位置",
            "重置悬浮窗位置",
            "设置",
            "选择游戏/乐器",
            "设置坐标",
            "MIDI设备连接",
            "检查权限",
            "自定义坐标",
            "延音设置",
            "选择目标游戏...",
            "选择目标乐器...",
            "选择目标键位...",
            "未选择游戏",
            "当前游戏没有可用的乐器！",
            "当前游戏没有可用的键位！",
            "设置没有改变",
            "设置已保存",
            "屏幕适配",
            "全面屏",
            "摄像头模组位于左侧",
            "摄像头模组位于右侧",
            "延音已开启",
            "延音已关闭",
            "高级选项",
            "频率时长：",
            "延迟：",
            "断音调低 建议范围：5-100",
            "卡顿调高 断音调低 建议范围：0-50",
            "当前配置:",
            "MIDI串流中...",
            "隐藏/显示主悬浮窗",
            "退出",
            "第五人格",
            "原神",
            "风物之诗琴",
            "老旧的诗琴",
            "自定义",
            "第一行",
            "第二行",
            "第三行",
            "列",
            "光遇",
            "确定",
            "取消"],  
        1 :
            ["語言",
            "繁體中文",
            "初始化設置..",
            "模組加載錯誤",
            "未找到合適配置, 已加載默認配置!",
            "加載配置檔失敗! 已自動加載默認配置!",
            "保存用戶遊戲配置成功",
            "錯誤",
            "沒有找到MIDI設備, 點擊確定重試, 點擊取消退出",
            "選擇MIDI設備",
            "打開設備失敗",
            "等待設備連接…",
            "您取消了選擇",
            "MIDI連接失敗！",
            "MIDI連接成功！",
            "此MIDI設備沒有可用的端口",
            "選擇MIDI端口",
            "等待無障礙服務...",
            "請打開 ",
            " 的無障礙許可權!",
            "無障礙許可權已開啟!",
            "無障礙服務已啟動",
            "請打開 ",
            " 的懸浮窗許可權!",
            "懸浮窗許可權已開啟",
            "請點擊",
            "最左上角按鍵的中心",
            "最右下角按鍵的中心",
            "定位第",
            "行 第",
            "個按鍵",
            "當前座標：",
            "，點擊'確定'結束, 點擊'取消'重新獲取",
            "座標不准? 手機上下翻轉後再嘗試",
            "或 手指直接點擊按鍵位置 忽略十字線位置偏差",
            "點擊調整位置",
            "重置懸浮窗位置",
            "設置",
            "選擇遊戲/樂器",
            "設置座標",
            "MIDI設備連接",
            "檢查許可權",
            "自定義座標",
            "延音設置",
            "選擇目標遊戲...",
            "選擇目標樂器...",
            "選擇目標鍵位...",
            "未選擇遊戲",
            "當前遊戲沒有可用的樂器！",
            "當前遊戲沒有可用的鍵位！",
            "設置沒有改變",
            "設置已保存",
            "螢幕適配",
            "全面屏",
            "攝像頭模組位於左側",
            "攝像頭模組位於右側",
            "延音已開啟",
            "延音已關閉",
            "高級選項",
            "頻率時長：",
            "延遲：",
            "斷音調低 建議範圍：5-100",
            "卡頓調高 斷音調低 建議範圍：0-50",
            "當前配置:",
            "MIDI串流中...",
            "隱藏/顯示主懸浮窗",
            "退出",
            "第五人格",
            "原神",
            "風物之詩琴",
            "老舊的詩琴",
            "自定義",
            "第一行",
            "第二行",
            "第三行",
            "列",
            "光遇",
            "確定",
            "取消"],
        2 : 
            ["Language",
            "English",
            "Initializing…",
            "Module loading error",
            "Appropriate configuration not found, default configuration loaded!",
            "Failed to load the configuration file, default configuration loaded!",
            "User game configuration saved",
            "Error",
            "Not Found MIDI device， Click OK to repeat,Click cancel to quit",
            "Choose MIDI device",
            "Fail to open device",
            "Wait device to connect",
            "You canceled choosing",
            "MIDI Connection Failed!",
            "MIDI Connection Success!",
            "This MIDI device has no available ports",
            "Choose MIDI ports",
            "Waiting for accessibility services...",
            "Please Open ",
            " accessibility Permission!",
            "Accessibility services have opened!",
            "Accessibility services have started!",
            "Please open ",
            " Floating window Permission!",
            "Floating window Permission has been opened",
            "Please Tap",
            "The center of the top-leftmost button",
            "The center of the bottom-rightmost button",
            "Locate the button in row ",
            " , column ",
            " .",
            "Current coordinates:",
            ", Click 'OK' to finish, click 'Cancel' to retrieve again.",
            "Coordinates inaccurate? Try flipping your phone upside down and try again.",
            "Or directly tap the button position with your finger, ignoring crosshair position deviation.",
            "Click to adjust position",
            "Reset floating window position",
            "Setting",
            "Choose Game/Instrumental",
            "Set Coordinates",
            "MIDI device connection",
            "Permission Check",
            "Customize coordinates",
            "Sustain settings",
            "Choose target game...",
            "Choose target instrumental...",
            "Choose target Key Position...",
            "Game not selected",
            "There are no available instruments in the current game!",
            "There are no available keys in the current game!",
            "Setting no changed",
            "Setting saved",
            "Screen adaptation",
            "Full screen",
            "Camera module on the Left side",
            "Camera module on the Right side",
            "Sustain Started",
            "Sustain Closed",
            "Advanced Option",
            "Frequency duration:",
            "Delay:",
            "Lower when disrupted tone.Suggested range:5-100",
            "Raise when stuttering, Lower when disrupted tone.Suggested range:0-50",
            "Current configuration:",
            "MIDI streaming...",
            "Hide/Show the main floating window",
            "Quit",
            "Identity V",
            "Genshin",
            "Windsong Lyre",
            "Vintage Lyre",
            "Customize Name",
            "Row1",
            "Row2",
            "Row3",
            "Column",
            "Sky",
            "OK",
            "Cancel"],        
        3 :
            ["言語",
            "日本語",
            "初期化中…",
            "モジュール読込みエラー",
            "適切な設定を見つかりません。デフォルトの設定を読み込まれました",
            "設定ファイルの読込みに失敗しました。デフォルトの設定が自動的に読み込まれました。",
            "ゲーム設定が保存されました",
            "エラー",
            "MIDI デバイスが見つかりません。[OK] をクリックして再試行します、もしくは[キャンセル] をクリックして終了します。",
            "MIDIデバイスを選択してください",
            "デバイスを開けませんでした",
            "デバイスの接続を待機中…",
            "選択をキャンセルしました",
            "MIDIに接続失敗しました",
            "MIDIに接続成功しました",
            "このMIDIデバイスには利用可能なポートがありません ",
            "MIDIポートを選択してください",
            "アクセシビリティ サービス起動するのを待っています",
            "アプリのアクセシビリティ権限を",
            "有効にしてください",
            "アクセシビリティ権限が有効になっています",
            "アクセシビリティ　サービスが開始されました",
            "アプリのフローティング ウィンドウ権限を",
            "有効にしてください",
            "フローティングウィンドウ権限が有効になっています",
            "クリックしてください",
            "左上隅のボタンの中央",
            "右下隅のボタンの中央",
            "この",
            "行目の",
            "番目のボタンに配置します",
            "現在の座標:",
            "「OK」をクリックして終了し、「キャンセル」をクリックして再取得します。",
            "座標が正確ではありませんか? 携帯電話を上下に反転して、もう一度お試しください",
            "もしくは、十字線の位置のずれを無視して、指で直接ボタンをクリックしてみてください",
            "クリックして位置を調整",
            "フローティング ウィンドウの位置をリセット",
            "設定",
            "ゲーム/楽器を選択します",
            "座標を設定します",
            "MIDIデバイスの接続",
            "権限を確認します",
            "座標のカスタマイズ",
            "サステイン設定",
            "対象のゲームを選択してください...",
            "対象の楽器を選択してください...",
            "対象のキーを選択してください...",
            "ゲームをまだ選択されていません",
            "対象のゲームに使用できる楽器がありません",
            "対象のゲームに使用できるキーがありません",
            "設定を変更しせん",
            "設定を保存されました",
            "画面の適応",
            "全画面",
            "左側のカメラモジュール",
            "右側のカメラモジュール",
            "サステインがオンになっています",
            "サステインがオフになっています",
            "詳細オプション",
            "周波数持続時間:",
            "遅延:",
            "トーンをなくなる場合下げてください、推奨範囲:5-100",
            "音声がカクカクの場合上げてください、推奨範囲:0-50",
            "現在の設定:",
            "MIDIストリーミング中...",
            "メインのフローティング ウィンドウの表示/非表示を切り替えます",
            "終了します",
            "アイデンティティ V",
            "原神",
            "風吹きのライアー",
            "古びたライアー",
            "名前をカスタマイズすします",
            "1行目",
            "2行目",
            "3行目",
            "列目",
            "Sky",
            "OK",
            "キャンセル"],
    };
    
    /**
     * 翻译
     * @param {*} tag - 第几条文本
     * @param {*} val - 语言
     * @param {string} key - 默认文本
     * @returns {string} 返回翻译文本，未选择语言则返回默认值
     */
    this.tsl = function (tag, val, key){
        if (val == -1){
            return key;
        } else {
            let text = LanguageText[val];
            return text[tag];
        }
    };
    
    /**
     * @brief 语言列表
     * @returns {Array<string>} 返回语言列表
     */
    this.getLanguageList = function () {
        return LanguageList;
    };
}

module.exports = new Language();